Fixing some issues on RIT workflow
rsksmart/powpeg-node pull request #312
Opened 2024-09-16 13:06 UTC by fmacleal

Issues fixed:
1 - Remove the trigger on push for master and *-rc -> we don't need that anymore since we are running it for every commit on PRs against these branches. 2 - Send the status of the execution to slack
3 - Solve the issue that the status of an execution triggered via workflow doesn't update the PR status. And if we need to use a different branch for RIT, Powpeg and RIT in the PR, it won't change the status to green after the workflow_dispatch execution -> We will do that adding a parsing on the description, looking for the branch that need to be used for that PR. If there is no branch configured on the description, we will try to use the default one.

Branches to be used by RIT:
fed:vovchyk/jackson-ver-bump
rskj:vovchyk/jackson-ver-bump

2024-09-16 14:03 UTC, Vovchyk requested changes
before we were expecting branch names inside back apostrophes, eg., \`fed:vovchyk/jackson-ver-bump\`. Could we continue doing it?

2024-09-20 15:40 UTC, lucasvuotto requested changes

2024-09-20 15:40 UTC, lucasvuotto commented on .github/workflows/rit.yml
> +          rit-branch: ${{ env. RIT_BRANCH }}
```suggestion
          rit-branch: ${{ env.RIT_BRANCH }}
```

2024-09-24 13:01 UTC, marcos-iov approved these changes

2024-09-24 13:14 UTC, Vovchyk approved these changes

2024-09-24 13:53 UTC, marcos-iov commented
pipeline:run

2024-09-24 14:30 UTC, merged